# Usagers et non usagers

Après avoir diagnostic l'établissement et son environnement, portons notre regard sur les usagers et les non usagers des médiathèques de notre territoire. Cette partie implique de réaliser une comparaison entre les données sur les publics de la médiathèque et la composition du territoire. La comparaison nous renseignera, en filigrane, sur les non-usagers des médiathèques. Il nous faut récupérer et visualiser ces deux types de données. 

On considère ici un usager comme une personne ayant fréquenté au moins une fois dans l’année un établissement de lecture publique et un non-usager comme une personne qui ne s’est pas rendue en bibliothèque depuis plus d’un an. 


## Données sur les usagers : l'observatoire de la lecture publique

Le ministère de la Culture collecte annuellement les données chiffrées de chaque bibliothèque territoriale. Ces données agrégées permettent d’alimenter et d’analyser les statistiques du ministère sur la lecture publique. Elles constituent également un moyen objectif pour les établissements de se connaitre, d’évaluer l’ensemble de leurs actions, mieux cerner leurs usagers, de réfléchir sur les non-usagers, et de s'interroger sur les pratiques culturelles ? 
 
C’est le rapport que vous remplissez chaque année par le biais de votre bibliothèque départementale ou directement sur internet. 
 
Les données compilées sont ensuite intégrées et mises à votre disposition dans l’Observatoire de la lecture publique, où un [outil cartographique](https://olp.culture.fr/#c=home) rend possible le croisement de certaines données et leur affichage par territoire.

Parmi les données du questionnaire, nous nous intéressons ici particulièrement aux données socio-économiques qui permettent une comparaison avec les statistiques publiques collectées par l'INSEE et les autres acteurs de la statistique publique. 

L'Observatoire de la lecture publique propose dans son outil de consultation des données uniquement des statistiques relatives aux caractéristiques des emprunteurs. 

Récupérer les données dans le questionnaire ? 

## Données socio-démographiques : découverte de l'outil regard cartographique sur nos terrtoires de la Région Sud

Le service Connaissance du territoire de la Région Sudpropose un ensemble d’outils pour permettre d’explorer un grand nombre d’indicateurs statistiques localisés, de les analyser, les comparer, les représenter, les cartographier, les exporter sur le site https://notreterritoire.maregionsud.fr/. 




