--- 
title: "Kit data des bibliothèques"
author: "Sylvain Lapoix et Samuel Goëta (Datactivist) pour l'Agence du Livre Aix Marseille Provence"
date: "`r format(Sys.Date(    ), '%d/%m/%Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Le kit data bibliothèque offre aux établissements souhaitant entamer une démarche d'extension des horaires des méthodes et outils pour inclure des analyses de données au bilan préalable."
---

# Introduction {-}

Ce kit vise à fournir aux bibliothèques souhaitant entamer une démarche d'extension des horaires d'ouverture les outils leur permettant de traiter les données disponibles pour documenter leur bilan.

Il se propose ainsi comme un complément du kit bibliothèque proposé par l'Agence régionale du livre Provence Alpes Côtes d'Azur. A cet égard, il s'attardera sur trois étapes que les données disponibles permettent de documenter de manière efficace :

1. Le diagnostic de l'établissement ;

2. Le diagnostic du territoire ;

3. Les usagers et non usagers.

Pour chaque partie, une fois les enjeux de données présentés, nous exposerons :

* la méthode de collecte des données ;

* un outil gratuit de visualisation ;

* des exemples pratiques de traitements et visualisations à intégrer à votre projet.

Ce kit est open source, il s'appuie sur le travail réalisé par Datactivist pour l'Agence régionale du livre Provence Alpes Côtes d'Azur. Ce kit est publié sous licence [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.fr) (Attribution - Partage dans les Mêmes Conditions 4.0 International) qui permet la réutilisation tout en garantissant que le contenu restera ouvert.